import { NgModule } from '@angular/core';
import {MatExpansionModule} from '@angular/material/expansion';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatSnackBarModule} from '@angular/material/snack-bar';
import { MatToolbarModule,
         MatCheckboxModule, 
         MatButtonModule,
         MatInputModule, 
         MatSidenavModule, 
         MatIconModule, 
         MatListModule,
         MatDatepickerModule,
         MatNativeDateModule,
         MatDialogModule,
         MatSelectModule,
         MatGridListModule,
         MatMenuModule,
         MatCardModule,
         MatBadgeModule}
 from '@angular/material';

@NgModule({
  imports: [MatButtonModule, 
            MatCheckboxModule,
            MatExpansionModule,
            MatFormFieldModule,
            MatInputModule,
            MatToolbarModule,
            MatSidenavModule,
            MatIconModule,
            MatListModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatDialogModule,
            MatSelectModule,
            MatGridListModule,
            MatMenuModule,
            MatCardModule,
            MatBadgeModule,
            MatSnackBarModule],
 exports: [MatButtonModule, 
           MatCheckboxModule,
           MatExpansionModule,
           MatFormFieldModule, 
           MatInputModule,
           MatToolbarModule,
           MatSidenavModule,
           MatIconModule,
           MatListModule,
           MatDatepickerModule,
           MatNativeDateModule,
           MatDialogModule,
           MatSelectModule,
           MatGridListModule,
           MatMenuModule,
           MatCardModule,
           MatBadgeModule,
           MatSnackBarModule
          ],
})
export class MaterialComponent { }